[workspace]
members = [
    "app",
    "core",
    "cli",
]


[profile.releasedebug]
inherits = "release"
debug = true


[profile.final]
inherits = "release"
strip = true
lto = true
codegen-units = 1
